INITIAL_MENU_ITEMS = [
    {
        "seed_key": "item-1",
        "category": "STARTER",
        "title": "Chicken Tikka",
        "description": "An extraordinary starter dish from India.",
        "price": "12.99",
        "is_special": False,
        "is_available": True,
        "src": "reservations/menu/menu-item-1.png",
    },
    {
        "seed_key": "item-2",
        "category": "STARTER",
        "title": "Chinese Roll",
        "description": "Chinese cuisine best starters roll.",
        "price": "9.50",
        "is_special": False,
        "is_available": True,
        "src": "reservations/menu/menu-item-2.png",
    },
    {
        "seed_key": "item-3",
        "category": "MAIN",
        "title": "Jan-Chan Ramen",
        "description": "Chinese Ramen created in Japan.",
        "price": "16.00",
        "is_special": True,
        "is_available": True,
        "src": "reservations/menu/menu-item-3.png",
    },
    {
        "seed_key": "item-4",
        "category": "STARTER",
        "title": "Veg-Olive Salad",
        "description": "Fresh olives mixed with seasonal salad.",
        "price": "10.00",
        "is_special": False,
        "is_available": True,
        "src": "reservations/menu/menu-item-4.png",
    },
    {
        "seed_key": "item-5",
        "category": "DESSERT",
        "title": "Choco Lava",
        "description": "Lava mixed chocolates with molten center.",
        "price": "8.50",
        "is_special": False,
        "is_available": True,
        "src": "reservations/menu/menu-item-5.png",
    },
    {
        "seed_key": "item-6",
        "category": "MAIN",
        "title": "Avocado Rice",
        "description": "Rice mixed with fresh seasoned avocados.",
        "price": "14.00",
        "is_special": False,
        "is_available": True,
        "src": "reservations/menu/menu-item-6.png",
    },
    {
        "seed_key": "item-7",
        "category": "STARTER",
        "title": "Truffle Fries",
        "description": "Crispy hand-cut fries tossed with parmesan and black truffle oil.",
        "price": "11.00",
        "is_special": False,
        "is_available": True,
        "src": "reservations/menu/menu-item-7.png",
    },
    {
        "seed_key": "item-8",
        "category": "STARTER",
        "title": "Garlic Butter Prawns",
        "description": "Sautéed jumbo prawns in garlic, butter, and white wine glaze.",
        "price": "15.50",
        "is_special": True,
        "is_available": True,
        "src": "reservations/menu/menu-item-8.png",
    },
    {
        "seed_key": "item-9",
        "category": "STARTER",
        "title": "Caprese Salad",
        "description": "Fresh heirloom tomatoes, buffalo mozzarella, and fresh basil drizzle.",
        "price": "12.00",
        "is_special": False,
        "is_available": True,
        "src": "reservations/menu/menu-item-9.png",
    },
    {
        "seed_key": "item-10",
        "category": "STARTER",
        "title": "Crispy Calamari",
        "description": "Lightly battered squid rings served with house spicy marinara.",
        "price": "13.50",
        "is_special": False,
        "is_available": True,
        "src": "reservations/menu/menu-item-10.png",
    },
    {
        "seed_key": "item-11",
        "category": "STARTER",
        "title": "Stuffed Mushrooms",
        "description": "Baked button mushrooms filled with herbs, garlic, and cream cheese.",
        "price": "10.50",
        "is_special": False,
        "is_available": False,
        "src": "reservations/menu/menu-item-11.png",
    },
    {
        "seed_key": "item-12",
        "category": "MAIN",
        "title": "Truffle Wagyu Steak",
        "description": "Prime aged Wagyu beef topped with black truffle butter.",
        "price": "45.00",
        "is_special": True,
        "is_available": True,
        "src": "reservations/menu/menu-item-12.png",
    },
    {
        "seed_key": "item-13",
        "category": "MAIN",
        "title": "Lobster Thermidor",
        "description": "Fresh lobster baked in a rich cognac and mustard cream sauce.",
        "price": "52.00",
        "is_special": True,
        "is_available": True,
        "src": "reservations/menu/menu-item-13.png",
    },
    {
        "seed_key": "item-14",
        "category": "MAIN",
        "title": "Grilled Atlantic Salmon",
        "description": "Pan-seared salmon fillet over lemon asparagus risotto.",
        "price": "24.00",
        "is_special": False,
        "is_available": True,
        "src": "reservations/menu/menu-item-14.png",
    },
    {
        "seed_key": "item-15",
        "category": "MAIN",
        "title": "Wild Mushroom Pasta",
        "description": "Fettuccine with roasted forest mushrooms in light garlic cream.",
        "price": "18.50",
        "is_special": False,
        "is_available": True,
        "src": "reservations/menu/menu-item-15.png",
    },
    {
        "seed_key": "item-16",
        "category": "MAIN",
        "title": "Chicken Parmesan",
        "description": "Breaded chicken breast topped with melted mozzarella and marinara.",
        "price": "19.00",
        "is_special": False,
        "is_available": True,
        "src": "reservations/menu/menu-item-16.png",
    },
    {
        "seed_key": "item-17",
        "category": "MAIN",
        "title": "BBQ Prime Ribs",
        "description": "Slow-roasted pork ribs glazed with signature honey smoked BBQ sauce.",
        "price": "28.00",
        "is_special": True,
        "is_available": True,
        "src": "reservations/menu/menu-item-17.png",
    },
    {
        "seed_key": "item-18",
        "category": "MAIN",
        "title": "Lamb Chops Supreme",
        "description": "Herb-crusted lamb chops served with roasted red potatoes.",
        "price": "34.00",
        "is_special": True,
        "is_available": False,
        "src": "reservations/menu/menu-item-18.png",
    },
    {
        "seed_key": "item-19",
        "category": "DESSERT",
        "title": "Chef Special Caviar Tart",
        "description": "Sweet dessert tart shell layered with fruit caviar pearls.",
        "price": "16.00",
        "is_special": True,
        "is_available": True,
        "src": "reservations/menu/menu-item-19.png",
    },
    {
        "seed_key": "item-20",
        "category": "DESSERT",
        "title": "Classic Tiramisu",
        "description": "Traditional Italian espresso-soaked ladyfingers with mascarpone.",
        "price": "9.00",
        "is_special": False,
        "is_available": True,
        "src": "reservations/menu/menu-item-20.png",
    },
    {
        "seed_key": "item-21",
        "category": "DESSERT",
        "title": "New York Cheesecake",
        "description": "Rich creamy cheesecake topped with fresh berry compote.",
        "price": "9.50",
        "is_special": False,
        "is_available": True,
        "src": "reservations/menu/menu-item-21.png",
    },
    {
        "seed_key": "item-22",
        "category": "DESSERT",
        "title": "Matcha Green Tea Pudding",
        "description": "Silky smooth Japanese matcha pudding with sweet red bean.",
        "price": "8.00",
        "is_special": False,
        "is_available": True,
        "src": "reservations/menu/menu-item-22.png",
    },
    {
        "seed_key": "item-23",
        "category": "DESSERT",
        "title": "Mango Passion Creme",
        "description": "Chilled tropical cream layered with real mango puree.",
        "price": "10.00",
        "is_special": True,
        "is_available": True,
        "src": "reservations/menu/menu-item-23.png",
    },
]
