# Generated by Django 6.1.1 on 2026-10-03 10:18

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BrowserSession",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=150)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("STARTER", "Starter"),
                            ("MAIN", "Main Course"),
                            ("DESSERT", "Dessert"),
                            ("DRINK", "Drink"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("src", models.CharField(max_length=500)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("is_special", models.BooleanField(default=False)),
                ("is_available", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="RestaurantSettings",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "capacity_per_slot",
                    models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("starts_at", models.DateTimeField(unique=True)),
                ("booked_seats", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=30)),
                (
                    "browser_session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer",
                        to="reservations.browsersession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "reference_code",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "guest_count",
                    models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_VERIFICATION", "Pending Email Verification"),
                            ("CONFIRMED", "Confirmed"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("EXPIRED", "Expired"),
                        ],
                        db_index=True,
                        default="PENDING_VERIFICATION",
                        max_length=25,
                    ),
                ),
                ("special_menu_eligible", models.BooleanField(default=False)),
                ("selected_menu_items", models.JSONField(blank=True, default=list)),
                ("customer_note", models.TextField(blank=True)),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="reservations.customer",
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="reservations.timeslot",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReservationOTP",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("otp_hash", models.CharField(max_length=64)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otp_attempts_history",
                        to="reservations.reservation",
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at"],
                "indexes": [
                    models.Index(fields=["reservation", "is_active"], name="otp_res_active_idx"),
                    models.Index(fields=["expires_at"], name="otp_expires_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(fields=["customer", "created_at"], name="res_cus_created_idx"),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(fields=["slot", "status"], name="res_slot_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.CheckConstraint(condition=models.Q(("guest_count__gte", 1)), name="res_guest_count"),
        ),
    ]
