# Generated by Django 6.1.1 on 2026-10-05 14:07

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_menuitem_seed_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantsettings',
            name='closing_time',
            field=models.TimeField(default=datetime.time(23, 0)),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='opening_time',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='slot_interval_minutes',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
