# Generated by Django 6.1.1 on 2026-10-09 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_menucategory_alter_menuitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='browser_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='reservations.browsersession'),
        ),
    ]
