# Generated by Django 6.1.1 on 2026-10-09 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_alter_customer_browser_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='browser_session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='reservations.browsersession'),
        ),
    ]
