from django.urls import path

from admin_portal.api.views.authentication import (
    AdminLoginView,
    AdminLogoutView,
    AdminMeView,
    AdminOTPVerifyView,
)
from admin_portal.api.views.dashboard import (
    AdminDashboardView,
    AdminPeakReservationHoursView,
    AdminReservationSlotPopularityView,
    AdminReservationTrendView,
    AdminTrendingFoodItemsView,
)
from admin_portal.api.views.menu import (
    AdminMenuCategoryDetailView,
    AdminMenuCategoryListView,
    AdminMenuItemDetailView,
    AdminMenuItemListView,
)
from admin_portal.api.views.reservations import (
    AdminReservationDetailView,
    AdminReservationListView,
)

urlpatterns = [
    path(
        "login/",
        AdminLoginView.as_view(),
        name="admin-login",
    ),
    path(
        "2fa/verify/",
        AdminOTPVerifyView.as_view(),
        name="admin-2fa-verify",
    ),
    path(
        "logout/",
        AdminLogoutView.as_view(),
        name="admin-logout",
    ),
    path(
        "me/",
        AdminMeView.as_view(),
        name="admin-me",
    ),
    path(
        "dashboard/",
        AdminDashboardView.as_view(),
        name="admin-dashboard",
    ),
    path(
        "dashboard/trends/",
        AdminReservationTrendView.as_view(),
        name="admin-dashboard-trends",
    ),
    path(
        "dashboard/peak-hours/",
        AdminPeakReservationHoursView.as_view(),
        name="admin-dashboard-peak-hours",
    ),
    path(
        "dashboard/slot-popularity/",
        AdminReservationSlotPopularityView.as_view(),
        name="admin-dashboard-slot-popularity",
    ),
    path(
        "dashboard/trending-food-items/",
        AdminTrendingFoodItemsView.as_view(),
        name="admin-trending-food-items",
    ),
    path(
        "reservations/",
        AdminReservationListView.as_view(),
        name="admin-reservation-list",
    ),
    path(
        "reservations/<uuid:reference_code>/",
        AdminReservationDetailView.as_view(),
        name="admin-reservation-detail",
    ),
    path(
        "menu/categories/",
        AdminMenuCategoryListView.as_view(),
        name="admin-menu-category-list",
    ),
    path(
        "menu/categories/<int:category_id>/",
        AdminMenuCategoryDetailView.as_view(),
        name="admin-menu-category-detail",
    ),
    path(
        "menu/items/",
        AdminMenuItemListView.as_view(),
        name="admin-menu-item-list",
    ),
    path(
        "menu/items/<int:menu_item_id>/",
        AdminMenuItemDetailView.as_view(),
        name="admin-menu-item-detail",
    ),
]
