# Generated by Django 6.1.1 on 2026-10-07 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminAccount",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=100, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password_hash", models.CharField(max_length=128)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("SUPER_ADMIN", "Super Admin"),
                            ("ADMIN", "Admin"),
                            ("RESERVATION_VIEWER", "Reservation Viewer"),
                            ("MENU_MANAGER", "Menu Manager"),
                        ],
                        default="ADMIN",
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="AdminLoginChallenge",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("otp_hash", models.CharField(max_length=64)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_challenges",
                        to="admin_portal.adminaccount",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["admin", "is_active"], name="admin_challenge_active_idx"),
                    models.Index(fields=["expires_at"], name="admin_challenge_exp_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AdminSession",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("last_activity_at", models.DateTimeField(auto_now=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="admin_portal.adminaccount",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["admin", "expires_at"], name="admin_session_exp_idx")],
            },
        ),
    ]
